### ISSUE TITLE
OpenEXR reader cannot be built on Mac and Windows 10

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgXchange#102]
Hi Robert,

the new OpenEXR reader code breaks the builds on MacOS 12.4 and Windows 10 with VS2022. The reason seems to be the same.
[xchange_win_err.txt](https://github.com/vsg-dev/vsgXchange/files/8833324/xchange_win_err.txt)
[xchange_max_err.txt](https://github.com/vsg-dev/vsgXchange/files/8833334/xchange_max_err.txt)

**Comment by robertosfield** [comment]
I had a quick look.  Mostly looks to be a OpenEXR version issue rather than platform one.  Which version of OpenEXR are you building against on Windows and MacOS?

**Comment by rainergericke** [comment]
I am using OpenEXR 3.1.5 on both systems.

**Comment by rainergericke** [comment]
I was able to make the build possible again. For Windows line 465 had to be changed from **Imf::InputFile file(filenameToUse.c_str());** to **Imf::InputFile file(filenameToUse.string().c_str());**. Replacing **Imf::Int64** by **uint64_t** did the rest on both machines. Now I have successful builds, but unfortunately only the Mac build can also read exr files. See attachments.
[openexr.cpp.zip](https://github.com/vsg-dev/vsgXchange/files/8837355/openexr.cpp.zip)
[sample_1280×853.exr.zip](https://github.com/vsg-dev/vsgXchange/files/8837356/sample_1280x853.exr.zip)

**Comment by robertosfield** [comment]
On Sat, 4 Jun 2022 at 10:20, Rainer Gericke ***@***.***>
wrote:

> I was able to make the build possible again. For Windows line 465 had to
> be changed from *Imf::InputFile file(filenameToUse.c_str());* to *Imf::InputFile
> file(filenameToUse.string().c_str());*. Replacing *Imf::Int64* by
> *uint64_t* did the rest on both machines. Now I have successful builds,
> but unfortunately only the Mac build can also read exr files. See
> attachments.
> openexr.cpp.zip
> <https://github.com/vsg-dev/vsgXchange/files/8837355/openexr.cpp.zip>
> sample_1280×853.exr.zip
> <https://github.com/vsg-dev/vsgXchange/files/8837356/sample_1280x853.exr.zip>
> Message ID: ***@***.***>

Thanks, fixes merged and submitted to vsgXchange OpenEXR branch.  I'll
merge with master next.

I tested your sample file:

    vsgviewer sample_1280×853.exr

And it renders it fine.  What Issue do you see under Windows?

**Comment by rainergericke** [comment]
On Windows there is only an error message like "this file could not be read".

**Comment by robertosfield** [comment]
On Sat, 4 Jun 2022 at 11:23, Rainer Gericke ***@***.***>
wrote:

> On Windows there is only an error message like "this file could not be
> read".
>
Could you run vsgviewer sample_1280×853.exr in a debugger with a break
point in the vsgXchange/src/openexr/openexr.cpp method:

    openexr::read(const vsg::Path& filename, vsg::ref_ptr<const
vsg::Options> options) const

And see what where it fails, either in the vsgXchange code in how we invoke
openexr?

FYI, I've just merged your changes into vsgXchange master.

**Comment by rainergericke** [comment]
Thanks, I loaded the last commits on Mac and Windows, both builds were successful. To my surprise I could read the sample exr file on both machines. There must be some magic in the game!

**Comment by robertosfield** [comment]
On Sat, 4 Jun 2022 at 14:37, Rainer Gericke ***@***.***>
wrote:

> Thanks, I loaded the last commits on Mac and Windows, both builds were
> successful. To my surprise I could read the sample exr file on both
> machines. There must be some magic in the game!
>

Any chance that the build of the VSG, vsgXchange and vsgExamples wasn't
consistent? Such as vsgExamples not being fully rebuilt against the updated
vsgXchange?  As the VSG defaults to static build it's easier to run an app
that hasn't been updated.

**Comment by rainergericke** [comment]
Yes that is possible. I also had an update of vs2022 in between.

Best

**Comment by robertosfield** [comment]
On Fri, 3 Jun 2022 at 16:48, Rainer Gericke ***@***.***>
wrote:

> I am using OpenEXR 3.1.5 on both systems.
>

At this point I suspect it's differences between OpenEXR 2.5.x and OpenEXR
3.x that is causing the problem.

I installed OpenEXR from the Ubunutu 21.10 repo, the version is:

$ sudo apt list libopenexr-dev
[sudo] password for robert:
Listing... Done
libopenexr-dev/impish,now 2.5.4-2 amd64 [installed]
libopenexr-dev/impish 2.5.4-2 i386

Could you have a bash at fixing compilation on 3.1.5 and then generate a
draft PR which I can test against 2.5.4 and see whether it builds fine, or
whether we'll have to juggle the code a bit to get it compile on both
systems.

Thanks,
Robert.
