### ISSUE TITLE
PNG textures from GLB models exported from blender are not loaded

### ISSUE THREAD

**Issue by Mikalai** [vsg-dev/vsgXchange#117]
Not sure if this is an issue of blender exporter which violates gltf rules or an issue in vsgXchange but found next case.

In SceneConverter::convertTexture in line 
`imageOptions->extensionHint = texture->achFormatHint;`

texture->achFormatHint contains just "png" without '.' and this leads to inability to parse data with following vsg::read_cast as reader looks like expects extension with '.'.

After modified code like shown below vsgviewer was able to load textured models from glb.

```
            if (texture->mWidth > 0 && texture->mHeight == 0)
            {
                auto imageOptions = vsg::Options::create(*options);
                imageOptions->extensionHint = texture->achFormatHint;
                
                if (!imageOptions->extensionHint.empty() && imageOptions->extensionHint[0] != '.')
                    imageOptions->extensionHint = vsg::Path(".") + imageOptions->extensionHint;

                if (samplerImage.data = vsg::read_cast<vsg::Data>(reinterpret_cast<const uint8_t*>(texture->pcData), texture->mWidth, imageOptions); !samplerImage.data.valid())
                    return {};
            }
```

Maybe this should be fixed in different way but would be nice to be able to handle such cases.

**Comment by robertosfield** [comment]
Could your provide a example model that reproduces this issue?

**Comment by robertosfield** [comment]
On Thu, 13 Oct 2022 at 10:18, Mikałaj ***@***.***> wrote:

> File is too big to upload it directly to github. It has repetitive
> subdivided models and big textures. Hope this link will work
> https://drive.google.com/drive/folders/117YL7Y3urNH7PlGJ-HqBd69UAaaN2Oe2?usp=sharing
>
> Thanks, I've downloaded the file and can load it with vsgviewer and see a
white untextured model.  I presume this is what you see and are expecting
it to be a textured model.

I have started putting debugging into the vsgXchange::assimp loader to look
at how it's handling the textures.  I'll try your suggestion of prepending
a . to the extension as this is now the standard for the VSG in line with
how std::filesystem does extensions.

**Comment by Mikalai** [comment]
Correct, without fix everything is white. With fix textures are loaded for models with materials that has texture and displayed correctly like blender did.

**Comment by robertosfield** [comment]
Testing board.glb and the .glb files in the glTF-Sample-Models all the embedded textures don't include the "." prefix so I have gone with a simple prefix of the  "." : bcf3eb0094b30afcc38068c383d815dd5335ea28

With this change the board.glb and the glTF-Sample-Models all load correctly now :-)
