### ISSUE TITLE
build fails due to typo

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgXchange#122]
In assimp.cpp line 668
**config->additionalDescrptorSetLayout = vdsl;**
should be replaced by
**config->additionalDescriptorSetLayout = vdsl;**

**Comment by robertosfield** [comment]
I've already fixed this (75e12d03086fa766b869982830f2f4043f6cd010), but haven't merged the associated branch yet.  I'm about to do the merge.

**Comment by robertosfield** [comment]
I have now merged the branch with the fix.
