### ISSUE TITLE
Problems reading forign files

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgXchange#135]
The foreign file import is faulty with the actual master commits:
vsgscreenshot --cf gipsy_master.png gipsy.3DS
gives:
![gipsy_master](https://user-images.githubusercontent.com/31243285/203931919-568cc03c-c83a-4cc5-9a29-5cb0a713e3f9.png)
vsgscreenshot --cf 2cylinder_master.png ...2CylinderEngine.gltf
leads to:
![2cylinder_master](https://user-images.githubusercontent.com/31243285/203932130-b6c76e73-2756-41d6-8424-3f573a293a2b.png)

Using the 1.0 release I got this:
![gipsy_release1 0](https://user-images.githubusercontent.com/31243285/203932434-5f68279e-d84a-4998-a681-58670eacb1d4.png)
and
![2cylinder_release1 0](https://user-images.githubusercontent.com/31243285/203932547-ac701b6e-2525-4534-8170-b2f9b0f538ea.png)

**Comment by robertosfield** [comment]
On Fri, 25 Nov 2022 at 08:12, Rainer Gericke ***@***.***>
wrote:

> The foreign file import is faulty with the actual master commits:
>
What is a "forien file import"?

I've never heard of the term.  What is --cf term for?

**Comment by rainergericke** [comment]
Seems to be an example for german english. A foreign file for me is a file format that is not native for vsg and needs translation via assimp routines like gltf, 3ds, lwo, obj, ..... While native file formats are vsgt and vsgb.

**Comment by rainergericke** [comment]
The --cf sets the output filename (and the format) of the color buffer output.

**Comment by robertosfield** [comment]
I have figured out the cause of the regression, a rather subtle one: 02f5bca9778976f6c67f97c4c69988ee66af7434

With this applied the 2CylinderEngine.gltf's lighting is restored.

**Comment by timoore** [comment]
Sorry about that! I realized last night that gltf models weren't working anymore and just now figured out that my "cleanup," to fix a warning, broke everything.
