### ISSUE TITLE
vsgconv misses functionalty

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgXchange#146]
After building vsgXchange from the actual repository I found following problems:

vsgconv bba.jpeg bba.cpp

![bba](https://user-images.githubusercontent.com/31243285/215827414-cd4b7886-b005-4167-8fa6-1ad35022b5d7.jpeg)

generates only a skeleton without data.
 
[bba_cpp.txt](https://github.com/vsg-dev/vsgXchange/files/10548835/bba_cpp.txt)

vsgconv shader.frag shader.cpp
[shader_frag.txt](https://github.com/vsg-dev/vsgXchange/files/10548857/shader_frag.txt)

[shader_cpp.txt](https://github.com/vsg-dev/vsgXchange/files/10548866/shader_cpp.txt)

does the same with a shader program.

On the Mac it is still possible to read non vsg 3d files (glb, obj...) and show it with vsgviewer.
On Windows does absolutely nothing with non vsg 3d files, no comment, no error.

**Comment by robertosfield** [comment]
I noticed an oddity with .cpp as well with it not writing out contents correctly, but haven't had a chance to investigate the regression yet.  When I hit the problem the --binary options still worked and that's what I needed anyway.

**Comment by robertosfield** [comment]
I have fixed the regression:  91d239ea3c52d426d80b5827758d0562ec8f4324

The problem was due to be tightening up the extension checking in vsg::VSG ReaderWriter.
