### ISSUE TITLE
can add one demo  show  how to use vsgXchange to load gltf  ?

### ISSUE THREAD

**Issue by WdsPjm** [vsg-dev/vsgXchange#149]

**Comment by robertosfield** [comment]
Many of the vsgExamples already can load GLTF files that to including vsgXchange in their setup, the pattern is:

```
auto options = vsg::Options::create();
options->add(vsgXchange::all::create());
auto model = vsg::read_cast<vsg::Node>("myfile.gltf", options);
```

There is also a section of vsgXchange in the vsgTutorial that I have begun writing:
https://vsg-dev.github.io/vsgTutorial/foundations/vsgXchange

**Comment by robertosfield** [comment]
I just checked the vsgXchange/README.md and it has a section that shows how to load a GLTF file:

https://github.com/vsg-dev/vsgXchange#how-to-use-vsgxchange-in-your-own-applications

So I can't help but feel that one just needs to read the documentation supplied.
