### ISSUE TITLE
Add a pull request template just like for the VulkanSceneGraph repository

### ISSUE THREAD

**Issue by LeeRiva** [vsg-dev/vsgXchange#161]
The subject says it all, I think this would be quite helpful

**Comment by robertosfield** [comment]
I'm torn on it.  I added it to the VSG as an experiment.  Issues with PRs still get through, does it reduce the chances?  Perhaps occasionally.

**Comment by LeeRiva** [comment]
I located the [vsg-dev pull request template](https://github.com/vsg-dev/VulkanSceneGraph/blob/master/.github/PULL_REQUEST_TEMPLATE.md), I'll maybe just use that one now that I know where to find it.
