### ISSUE TITLE
vsgXchange fails to compile

### ISSUE THREAD

**Issue by LeeRiva** [vsg-dev/vsgXchange#182]
> 1>------ Build started: Project: vsgXchange, Configuration: Debug x64 ------
1>assimp.cpp
1>X:\git\vsg\vsgXchange\src\assimp\assimp.cpp(145,13): error C2653: 'vsgXchange_assimp': is not a class or namespace name
1>Done building project "vsgXchange.vcxproj" -- FAILED.

I think `vsgXchange_assimp::SceneConverter converter;` should be `SceneConverter converter;` ?

**Comment by robertosfield** [comment]
I have been building on Linux and Windows 11 today and haven't seen problems.  What platform are you working on?

**Comment by robertosfield** [comment]
I have looked into the code the vsgXchange_assimp:: will have been a short experiment that got left in by accident.  I have removed it and checked the fix into vsgXchange master: d9bd957b898a5422d8aff4483ebb3670e362c470

The oddity is that it was compiling, I can only guess that as vsgXchange_assimp is a #define it was somehow working on my system.
