### ISSUE TITLE
Issues with materials on obj files

### ISSUE THREAD

**Issue by TheShed412** [vsg-dev/vsgXchange#201]
I am attempting to load an OBJ file that has a material file.

When the model loads, the model will load, but the material will not.

Here is the model in blender:
![ship_blender](https://github.com/user-attachments/assets/c61b8c15-83e7-497d-8bd8-e369668c13c7)

This is it when I load it in a simple viewer based off of the hello world tutorial:
![ship_vsg](https://github.com/user-attachments/assets/8b992b47-91c7-4401-966d-d975555599be)

I am loading the model like this:
```
auto options = vsg::Options::create(vsgXchange::all::create());
auto model = vsg::read_cast<vsg::Node>("models/ship2.obj", options);
```

I am fairly new to the vsg/osg libraries so this could be something I am doing wrong.

Here is a zip of the model and a vsgt file I created using the cli tool:
[ship.tar.gz](https://github.com/user-attachments/files/17004633/ship.tar.gz)

From what I can tell, the vsgt file has the material data in it, I am just not sure why it isn't loading.

I haven't seen any examples that convert directly from obj, so I wasn't sure if this was fully supported/tested.

I have also tried with fbx with the same result.

**Comment by robertosfield** [comment]
The model loads fine for me:

~~~ sh
vsgviewer ship.obj
~~~

![image](https://github.com/user-attachments/assets/a17f22a8-e453-4237-8086-b9930edf32d0)

What version of VSG, vsgXchange and Assimp are you using?

What OS, hardware and drivers are you using?

I'm using Kubuntu 24.04 + Intel iCore7 and it's Xe iGPU + mesa drivers, with VSG and vsgXchange master + Assimp 5.3.

**Comment by TheShed412** [comment]
VSG, and vsgXchange I am on master.

Assimp I just built from source on the tip of master as well. It seems to be a few commits ahead of v5.4.3.

I am using Linux Mint 20.3

Graphics I am almost positive I am using my dedicated nvidia card with driver version 470.239.06
It seems like that is being used by other processes.

Though when I run the example I am getting this on the command line:
`MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0`

So could it be that Vulkan/VSG is trying to use my Intel GPU instead of my dedicated GPU? This laptop seems to have a Intel i5-8300H, which I'm not sure of the status of Vulkan on. But I am almost certain my GPU is being used properly because all of my setting have the driver I listed before as the one in use. and in my PRIME settings it is set to always use the GPU.

**Comment by TheShed412** [comment]
Just now I attempted that sysctl command it suggested, it got rid of that warning, but still same result with the materials.

**Comment by robertosfield** [comment]
I have several machines with different hardware, a Windows Intel desktop with NVidia card, and Kubuntu  22.04 dekstop with AMD 5700G integrated graphics) and Kubuntu 24.04 latop to Intel iCore7 + integrated graphics.)  All produce close to identical results - Vulkan drivers looks to be much more consistent than OpenGL drivers.

In your case it sounds like your drivers aren't the NVidia drivers, but can't say why - I haven't used Linux Mint for over a decade.  The vsgExamples repo has a vsgdeviceselection example that illustrates querying capabilities of the hardware devices/drivers, to the list the devices and drivers run: 

~~~ sh
vsgdeviceselection --list
~~~

This is what I seen on this Intel/Kubuntu 24.04 laptop:

~~~ sh
$ vsgdeviceselection --list
vkEnumerateInstanceVersion() 4206867
VK_API_VERSION = 1.3.275.0

physicalDevices.size() = 2
    matched ref_ptr<vsg::PhysicalDevice>(vsg::PhysicalDevice 0x79986d55be4c) Intel(R) Xe Graphics (TGL GT2), deviceType = 1, apiVersion = 1.3.274, driverVersion = 24.0.9
    QueueFamilyProperties 1
        VkQueueFamilyProperties[0] queueFlags = GRAPHICS | COMPUTE | TRANSFER | SPARSE_BINDING | PROTECTED, queueCount = 1, timestampValidBits = 36, minImageTransferGranularity = {1, 1, 1}

    matched ref_ptr<vsg::PhysicalDevice>(vsg::PhysicalDevice 0x79986d55c2c0) llvmpipe (LLVM 17.0.6, 256 bits), deviceType = 4, apiVersion = 1.3.274, driverVersion = 0.0.1
    QueueFamilyProperties 1
        VkQueueFamilyProperties[0] queueFlags = GRAPHICS | COMPUTE | TRANSFER, queueCount = 1, timestampValidBits = 64, minImageTransferGranularity = {1, 1, 1}
~~~

So I have two different "devices" reported, the first is the integrated GPU and it's driver, then llvmpipe which is a software driver.  The VSG will be default select dedicated GPUs over integrated GPUs over software drivers, but you can select a specific one if you want to override this default.  The vsgdeviceselection example has --selection <num> option for selecting which one to use:

Hardware driver:
~~~ sh
$ vsgdeviceselection --select 0
vkEnumerateInstanceVersion() 4206867
VK_API_VERSION = 1.3.275.0
Selected vsg::PhysicalDevice ref_ptr<vsg::PhysicalDevice>(vsg::PhysicalDevice 0x7396c04ffe4c) Intel(R) Xe Graphics (TGL GT2) deviceType = 1
~~~

Software driver:
~~~ sh
$ vsgdeviceselection --select 1
vkEnumerateInstanceVersion() 4206867
VK_API_VERSION = 1.3.275.0
Selected vsg::PhysicalDevice ref_ptr<vsg::PhysicalDevice>(vsg::PhysicalDevice 0x7faf253002c0) llvmpipe (LLVM 17.0.6, 256 bits) deviceType = 4
~~~

**Comment by TheShed412** [comment]
so running that command I get this:
```
vkEnumerateInstanceVersion() 4202627

physicalDevices.size() = 3
    matched ref_ptr<vsg::PhysicalDevice>(vsg::PhysicalDevice 0x7ff5c06eeddc) Intel(R) UHD Graphics 630 (CFL GT2), deviceType = 1, apiVersion = 4202678, driverVersion = 88088582
    QueueFamilyProperties 1
        VkQueueFamilyProperties[0] queueFlags = GRAPHICS | COMPUTE | TRANSFER, queueCount = 1, timestampValidBits = 36, minImageTransferGranularity = {1, 1, 1}

    matched ref_ptr<vsg::PhysicalDevice>(vsg::PhysicalDevice 0x7ff5c06ef250) llvmpipe (LLVM 12.0.0, 256 bits), deviceType = 4, apiVersion = 4198582, driverVersion = 1
    QueueFamilyProperties 1
        VkQueueFamilyProperties[0] queueFlags = GRAPHICS | COMPUTE | TRANSFER, queueCount = 1, timestampValidBits = 64, minImageTransferGranularity = {1, 1, 1}

    matched ref_ptr<vsg::PhysicalDevice>(vsg::PhysicalDevice 0x7ff5c06ef6c4) Quadro P600, deviceType = 2, apiVersion = 4202671, driverVersion = 1975239040
    QueueFamilyProperties 3
        VkQueueFamilyProperties[0] queueFlags = GRAPHICS | COMPUTE | TRANSFER | SPARSE_BINDING, queueCount = 16, timestampValidBits = 64, minImageTransferGranularity = {1, 1, 1}
        VkQueueFamilyProperties[1] queueFlags = TRANSFER | SPARSE_BINDING, queueCount = 2, timestampValidBits = 64, minImageTransferGranularity = {1, 1, 1}
        VkQueueFamilyProperties[2] queueFlags = COMPUTE | TRANSFER | SPARSE_BINDING, queueCount = 8, timestampValidBits = 64, minImageTransferGranularity = {1, 1, 1}
```
It looks like it is seeing both the intel and nvidia gpus. I manually selected 2 just in case it was defaulting to the intel.

I also rebuilt the examples since I built them before installing assimp, and vsgviewer is now giving me the proper ship materials! I can look in to that viewer to see what I am doing wrong on my end.

**Comment by robertosfield** [comment]
The VSG by default builds as static so if you built vsgExamples prior to building vsgXchange against Assimp the previously built examples, including vsgviewer, will not have the full support of vsgXchange.  It's best to build the VSG then vsgXchange then any other VSG projects like vsgQt/vsgImGui then vsgExamples.

**Comment by TheShed412** [comment]
I figured it out! I was using the RenderGraph incorrectly in my stuff. Closing.
