### ISSUE TITLE
CMake fails due to curl

### ISSUE THREAD

**Issue by fgarlin** [vsg-dev/vsgXchange#31]
Hi,

The CMake compilation fails for me when checking for curl, both when it's installed and when it's not.

```
CMake Error at src/CMakeLists.txt:60 (add_library):
  Cannot find source file:

    curl/CURL_fallback.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
```

I think it's due to a typo on `src/curl/build_vars.cmake` where `if(${vsgXchange_GDAL})` should be `if(${vsgXchange_CURL})`, although it could be something else. Changing that fixes it for me though.

**Comment by robertosfield** [comment]
Well spotted, your suggested fix is correct - I didn't spot it as I have GDAL installed. I have applied the suggested fix and checked it into the vsgXchange master and the CURL branch.
