### ISSUE TITLE
Request support for vcpkg installation

### ISSUE THREAD

**Issue by w4454962** [vsg-dev/vsgXchange#39]
Vcpkg is a cross platform C + + package manager, the current project relies on many third-party libraries, hope to join the package manager, one click installation, easy to build environment

**Comment by robertosfield** [comment]
I don't personally have the time available to learn how to implement, implement and then maintain vcpkg support.  I'm happy for yourself and other interested dev contributing it.  I have created a thread on vsg-users for yourself and others to coordinate efforts.
