### ISSUE TITLE
can't build with newest version of VSG under windows 10

### ISSUE THREAD

**Issue by 16uhrpasing** [vsg-dev/vsgXchange#51]
hi,

the newest version of vsgxchange won't build with the newest version of VSG under windows 10 and CMake.

CMake throws the following error:
(my build directory: G:/git/build/VulkanSceneGraph)
(my source directory: G:/git/VulkanSceneGraph)

```
CMake Error at G:/git/build/VulkanSceneGraph/vsgConfig.cmake:20 (include):
  include could not find requested file:

    G:/git/build/VulkanSceneGraph/vsgMacros.cmake

Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)

CMake Error at G:/git/build/VulkanSceneGraph/vsgConfig.cmake:21 (include):
  include could not find requested file:

    G:/git/build/VulkanSceneGraph/vsgTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)


CMake Error at CMakeLists.txt:23 (vsg_setup_build_vars):
  Unknown CMake command "vsg_setup_build_vars".
```

Which makes sense, because the vsgMacros and vsgTargets file is not directly located in the build directory, but in some folders beneath: 

vsgMacros.cmake actual locations:
(build) C:\git\build\VulkanSceneGraph\lib\cmake\vsg
(source) G:\git\VulkanSceneGraph\cmake

vsgTargets.cmake actual locations:
(build) G:\git\build\VulkanSceneGraph\src\vsg\CMakeFiles\Export\lib\cmake\vsg
(build) G:\git\build\VulkanSceneGraph\lib\cmake\vsg

This is because the VSG build directory specifies the following lines in the file "vsgConfig.cmake" in line 20 and 21

include("${CMAKE_CURRENT_LIST_DIR}/vsgMacros.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/vsgTargets.cmake")

which is the wrong path. I fixed my installation by just inserting the absolute path to the files. I can't make a pull request of a fix since i don't know whether the files are not being copied to the right path or being referenced incorrectly.

**Comment by 16uhrpasing** [comment]
the vsgXchangeConfig.cmake file also references an invalid path to vsgXchangeTargets.cmake and i replaced it with an absolute path to build vsgExamples with it

**Comment by rhabacker** [comment]
Building the vsgXchange source depends on an installed VulkanSceneGraph build. See the following example, which uses  the cmake "NMake Makefiles" generator:

1. open  MSVC development prompt
2. build vsg
```
cd <development-root>
git clone https://github.com/vsg-dev/VulkanSceneGraph.git
mkdir VulkanSceneGraph-build
cd VulkanSceneGraph-build
cmake ../VulkanSceneGraph -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=<development-root>/vsg-install
nmake
nmake install
```
3. Then build vsgXchange
```
cd <development-root>
git clone https://github.com/vsg-dev/vsgXchange.git
mkdir vsgXchange-build
cd vsgXchange-build
cmake ../vsgXchange -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=<development-root>/vsg-install -DCMAKE_PREFIX_PATH=<development-root>/vsg-install
nmake
nmake install
```

**Comment by robertosfield** [comment]
Is this simply a documentation issue?  Not following existing documentation?

@rhabacker  the nmake example you provide could be a good addition to existing documentation.

I'm open to suggestions/PR's :-)
