### ISSUE TITLE
The cmake build system does not check the minimum required osg version

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/vsgXchange#52]
**Describe the error**
A colleague reported that creating vsg with osg 3.4 (which is the version still used by a maintained application) fails with the following error: 
```
F:\cegit\64bit-vk\git\vsgXchange\src\osg\ImageUtils.cpp(245): error C2065: "GL_COMPRESSED_RGBA_ASTC_4x4_KHR": undeclared identifier
F:\cegit\64bit-vk\git\vsgXchange\src\osg\ImageUtils.cpp(246): error C2065: "GL_COMPRESSED_RGBA_ASTC_5x4_KHR": undeclared identifier
F:\cegit\64bit-vk\git\vsgXchange\src\osg\ImageUtils.cpp(247): error C2065: "GL_COMPRESSED_RGBA_ASTC_5x5_KHR": undeclared identifier
F:\cegit\64bit-vk\vsgXchange\src\osg\ImageUtils.cpp(248): error C2065: "GL_COMPRESSED_RGBA_ASTC_6x5_KHR": undeclared identifier
```
**Reproduce**.
1. build vsgXchange with the osg version mentioned. 
2. see error

**Expected behavior**.
The build error should not occur

**Desktop (please fill in the following information):**
 - OS: Windows 10
 - MSVC: 2017 

**Additional Context**.
The cmake build system should check if the development package is available for osg version >= 3.5.8, as the listed identifiers were introduced with this version.

**Comment by robertosfield** [comment]
Adding the missing #define's would another solution to building against older OSG and gl.h  versions.

**Comment by rhabacker** [comment]
Is osg 3.4 a supported branch ?

**Comment by robertosfield** [comment]
On Tue, 21 Sept 2021 at 09:18, Ralf Habacker ***@***.***>
wrote:

> Is osg 3.4 a supported branch ?
>
Supported by the VSG?  Or more a support OSG version?

My focus for the OSG is now supporting the OSG-3.6.x branch.  I do still
merge fixes to 3.4 when members of the community push them.  I'm pretty
stretched thinly right now so haven't done as much OSG support work as I'd
like.

**Comment by rhabacker** [comment]
I don't think backporting will work here as the two branches have drifted too far apart. 

After `cherry-picking` the following commits from the 3.6 branch 
```
 (HEAD -> OpenSceneGraph-3.4) Updated osgAnimation
 Fixed build error
 Moved brackets to be consistent with the rest of the OSG
 added support for dxt compressed images to createImageWithOrientationConversion
 copySubImage support for block compressed images, added support for astc compressed type.
 added dxtc support to Image::getColor, extended Image::isImageTranslucent to test opacity of dxt3 and dxt5 images
```
and fix some merge conflicts there are still build errors 

Translated with www.DeepL.com/Translator (free version)

**Comment by robertosfield** [comment]
To fix the build against OSG-3.4.x what I meant just adding the #define's
to vsgXchange's OSG plugin, rather than cherry-picking additions back to
OSG-3.4.

**Comment by rhabacker** [comment]
But that would result in the constants being present but not used in osg because incomplete. 
I think there is another solution that can be done entirely in vsgXchange without any drawbacks, by excluding the constants in question if osg does not support them:
``` 
vsg::ref_ptr<vsg::Data> convertCompressedImageToVsg(const osg::Image* image)
    {
...
#if OSG_MIN_VERSION_REQUIRED(3,5,8)
        case (GL_COMPRESSED_RGBA_ASTC_4x4_KHR):
         ...
        case (GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR):
#endif
```

Translated with www.DeepL.com/Translator (free version)

**Comment by rhabacker** [comment]
That solution will also not work, as there are more build errors using HEAD from OpenSceneGraph-3.4 branch
```
/home/xxx/src/vsgXchange/src/osg/ConvertToVsg.cpp:169:23: error: ‘QuatArrayType’ is not a member of ‘osg::Array’
     case (osg::Array::QuatArrayType): return {};
                       ^~~~~~~~~~~~~
/home/xxx/src/vsgXchange/src/osg/ConvertToVsg.cpp:171:23: error: ‘UInt64ArrayType’ is not a member of ‘osg::Array’
     case (osg::Array::UInt64ArrayType): return {};
                       ^~~~~~~~~~~~~~~
/home/xxx/src/vsgXchange/src/osg/ConvertToVsg.cpp:172:23: error: ‘Int64ArrayType’ is not a member of ‘osg::Array’
     case (osg::Array::Int64ArrayType): return {};
                       ^~~~~~~~~~~~~~
/home/xxx/src/vsgXchange/src/osg/OSG.cpp: In member function ‘vsg::ref_ptr<vsg::Object> vsgXchange::OSG::Implementation::read(const Path&, vsg::ref_ptr<const vsg::Options>) const’:
/home/xxx/src/vsgXchange/src/osg/OSG.cpp:235:46: error: ‘class osg::Object’ has no member named ‘asImage’
     else if (osg::Image* osg_image = object->asImage(); osg_image != nullptr)
                                              ^~~~~~~
```
It looks that setting the minimum required version for OSG to 3.5.8 is the only solution.

**Comment by robertosfield** [comment]
Hi Ralf,


The "#if OSG_MIN_VERSION_REQUIRED(3, 5, 8)" approach feels OK.  The
asImage() could easily be replaced by a dynamic_cast<osg::Image> and
would allow the codebase to work the same for the various versions of
the OSG.

If you want to get that working against 3.4 then I'd be happy to merge the PR.

**Comment by robertosfield** [comment]
Do any of these OSG-3.4 related warnings have relevance to the vsgXchange's
OSG loader?  If not then I don't see a problem with just quieting the
warning level down for the OSG includes.  Not enabling support for OSG-3.4
simply because modern compilers issue more warnings than occurred when
OSG-3.4 was released seems a bit unfair on OSG-3.4 users.

**Comment by rhabacker** [comment]
> Do any of these OSG-3.4 related warnings have relevance to the vsgXchange's OSG loader? 

Cannot say yet, as it would require to get very deep into that stuff.

Instead I make a build for vsgXchange with OSG 3.4 and did run
``` 
$ bin/vsgconv  ~/src/OpenSceneGraph-data/dumptruck.osg dumptruck.vsgt
$ osgviewer  ~/src/OpenSceneGraph-data/dumptruck.osg --window 0 0 1050 1050 &
$ vsgviewer dumptruck.vsgt &
```
and got ![image](https://user-images.githubusercontent.com/602903/134477532-8286222b-4fe5-4b1b-a1ae-8a72d5a0e2ab.png)

**Comment by robertosfield** [comment]
Hi Ralf,

On Thu, 23 Sept 2021 at 09:39, Ralf Habacker ***@***.***>
wrote:

> Do any of these OSG-3.4 related warnings have relevance to the
> vsgXchange's OSG loader?
>
> Cannot say yet, as it would require to get very deep into that stuff.
>
> Instead I make a build for vsgXchange with OSG 3.4 and did run
>
> $ bin/vsgconv  ~/src/OpenSceneGraph-data/dumptruck.osg dumptruck.vsgt
> $ osgviewer  ~/src/OpenSceneGraph-data/dumptruck.osg --window 0 0 1050 1050 &
> $ vsgviewer dumptruck.vsgt &
>
> That;s the same result you'd get with OSG-3.6.x and master.  The shaders
that Tom Hogarth wrote don't 1:1 match OpenGL fixed function pipeline, for
instance with Tom's shaders you get per pixel lighting :-)

Longer term my plan is to come up with a set of shaders that support the
OSG loaders as well as Assimp, and have these support multiple light
sources etc.  I'd like to tackle this prior to VSG-1.0.

Robert.
