### ISSUE TITLE
vsgXchange doesn't build on MacOS

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgXchange#6]
Using the latest repositories of vsg and vsgXchange I get a build error:

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/rainerge/Soft/Entwicklung/VSG/vsgXchange
Scanning dependencies of target vsgXchange
[  5%] Building CXX object src/CMakeFiles/vsgXchange.dir/vsgXchange/ShaderCompiler.cpp.o
[ 11%] Building CXX object src/CMakeFiles/vsgXchange.dir/vsgXchange/ReaderWriter_all.cpp.o
[ 17%] Building CXX object src/CMakeFiles/vsgXchange.dir/glsl/ResourceLimits.cpp.o
/Users/rainerge/Soft/Entwicklung/VSG/vsgXchange/src/glsl/ResourceLimits.cpp:143:21: error: excess elements in scalar initializer
    /* .limits = */ {
                    ^
1 error generated.
make[2]: *** [src/CMakeFiles/vsgXchange.dir/glsl/ResourceLimits.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/vsgXchange.dir/all] Error 2
make: *** [all] Error 2

**Comment by robertosfield** [comment]
Which version of glslang do you have on your system? The GLSLANG_PATCH_LEVEL value is something I've used in the same code block to handle builds against different versions of glslang so it looks like we'll need to add something similar here once we know what version you have.

**Comment by rainergericke** [comment]
glslc --version
shaderc v2020.1-dev v2020.0-15-gb4a735c
spirv-tools v2020.3 v2020.3
glslang 8.13.3743-39-gd39b8afc

Target: SPIR-V 1.0

**Comment by rainergericke** [comment]
Actually this problem does not exist anymore.
