### ISSUE TITLE
Build vsgXchage with CURL failed

### ISSUE THREAD

**Issue by jakexie** [vsg-dev/vsgXchange#61]
MSVC print error: "can not find file "curl/curl.h". 
Error fixed after add line:"set(EXTRA_INCLUDES ${EXTRA_INCLUDE} ${CURL_INCLUDE_DIR})" at  "src/curl/build_vars.cmake:14".
@robertosfield

**Comment by robertosfield** [comment]
Could you generate a PR for this change, I'll then do a review and test. Thanks.

**Comment by jakexie** [comment]
> Could you generate a PR for this change, I'll then do a review and test. Thanks.

@robertosfield Hello! I just create a PR for this change.

**Comment by robertosfield** [comment]
Thanks, now merged.  FYI, for indentation we uses spaces in the VSG codebase and CMake files to avoid differences in appearance across platforms.
