### ISSUE TITLE
Compile error with assimp version 5.1.0

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/vsgXchange#65]
Compiling vsgXChange with assimp version 5.1.0 let the build fail with the following error:
```
[   56s] cd /home/abuild/rpmbuild/BUILD/vsgXchange-0.0.1+20211116+git.4573b9f/build/src && /usr/bin/c++  -DBASISD_SUPPORT_FXT1=0 -DBASISU_NO_ITERATOR_DEBUG_LEVEL -DKHRONOS_STATIC -DKTX_FEATURE_KTX1 -DKTX_FEATURE_KTX2 -DLIBKTX -DUSE_FREETYPE -DVSG_SHARED_LIBRARY -DvsgXchange_EXPORTS -I/home/abuild/rpmbuild/BUILD/vsgXchange-0.0.1+20211116+git.4573b9f/include -I/home/abuild/rpmbuild/BUILD/vsgXchange-0.0.1+20211116+git.4573b9f/build/include -I/home/abuild/rpmbuild/BUILD/vsgXchange-0.0.1+20211116+git.4573b9f/src/ktx/libktx -I/usr/include/freetype2  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -O2 -g -DNDEBUG -fPIC   -Wall -Wparentheses -Wno-long-long -Wno-import -Wreturn-type -Wmissing-braces -Wunknown-pragmas -Wmaybe-uninitialized -Wshadow -Wunused -Wno-misleading-indentation -Wextra -std=gnu++1z -o CMakeFiles/vsgXchange.dir/assimp/assimp.cpp.o -c /home/abuild/rpmbuild/BUILD/vsgXchange-0.0.1+20211116+git.4573b9f/src/assimp/assimp.cpp
[   56s] /home/abuild/rpmbuild/BUILD/vsgXchange-0.0.1+20211116+git.4573b9f/src/assimp/assimp.cpp: In member function 'vsgXchange::assimp::Implementation::BindState vsgXchange::assimp::Implementation::processMaterials(const aiScene*, vsg::ref_ptr<const vsg::Options>) const':
[   56s] /home/abuild/rpmbuild/BUILD/vsgXchange-0.0.1+20211116+git.4573b9f/src/assimp/assimp.cpp:466:23: error: 'AI_MATKEY_GLTF_PBRSPECULARGLOSSINESS' was not declared in this scope
[   56s]          material->Get(AI_MATKEY_GLTF_PBRSPECULARGLOSSINESS, hasPbrSpecularGlossiness);
[   56s]                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   56s] /home/abuild/rpmbuild/BUILD/vsgXchange-0.0.1+20211116+git.4573b9f/src/assimp/assimp.cpp:466:23: note: suggested alternative: 'AI_MATKEY_COLOR_SPECULAR'
[   56s]          material->Get(AI_MATKEY_GLTF_PBRSPECULARGLOSSINESS, hasPbrSpecularGlossiness);
[   56s]                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   56s]                        AI_MATKEY_COLOR_SPECULAR
```
[_log.txt](https://github.com/vsg-dev/vsgXchange/files/7552684/_log.txt)

**Comment by rhabacker** [comment]
The definition in question was removed by this [commit](https://github.com/assimp/assimp/commit/44763528829fec49c46b6462df0d42a6451191e1).

**Comment by robertosfield** [comment]
I've come across this issue a month ago and had to bash resolving the
issues, it turns out not to be just a case of new variable/enum naming, how
PBR is handled has changed substantially and will require a rewrite on
outside, then it leaves the question of whether we can support both 5.1.0
and older versions.

**Comment by rhabacker** [comment]
>  whether we can support both 5.1.0 and older versions.

What is necessary to know to decide that ? 

Without knowing these differences in detail, different code can be implemented with 
``` 
#include <assimp/revision.h>
#if VER_MAJOR == 5 && VER_MINOR == 0
// Code for 5.0
#else
// code for 5.1
#endif
```

**Comment by robertosfield** [comment]
On Thu, 2 Dec 2021 at 14:10, Ralf Habacker ***@***.***> wrote:

> whether we can support both 5.1.0 and older versions.
>
> What is necessary to know to decide that ?
>
> Without knowing these differences in detail, different code can be
> implemented with
>
> #include <assimp/revision.h>
> #if VER_MAJOR == 5 && VER_MINOR == 0
> // Code for 5.0
> #else
> // code for 5.1
> #endif
>
>
I did a pass at trying this approach but the changes are pretty structural,
there isn't an easy 1:1 replacement.  The big problem area is that the PBR
support has been refactored.  After a day trying hack a solution I gave up
and abandoned by attempt at getting things compiled.

The changes to Assimp's PBR support will hopefully settle down and be
easier to adopt.  It may be that we need to pull in Assimp source code and
build specific tags.  I don't know yet the best path.

Robert.


>

**Comment by rhabacker** [comment]
>  It may be that we need to pull in Assimp source code

To build assimp version 5.0, vsgFramework would need to compile the `assimp_5.0_release` branch, which unfortunately requires fixes for use on x86_64 distributions that have a 'lib64' library subdirectory.

**Comment by robertosfield** [comment]
On Thu, 2 Dec 2021 at 14:28, Ralf Habacker ***@***.***> wrote:

> It may be that we need to pull in Assimp source code
>
> To build assimp version 5.0, vsgFramework would need to compile the
> assimp_5.0_release branch, which unfortunately requires fixes for use on
> x86_64 distributions that have a 'lib64' library subdirectory.
>
> I have several core VSG issues to tackle this week, so I won't be able to
address the problems with Assimp support right away.  Frustrating that a
Assimp 5.x release series wouldn't be more settled in API and cross
platform build support, but alas that's just what we have to deal with.

It may be that we just have to port to 5.1 and build it locally as part of
the vsgXchange to avoid these issues.

>

**Comment by kimkulling** [comment]
Hi, sorry for the inconvenience from our side! I will try to keep ABi-compatibility more stable.

**Comment by robertosfield** [comment]
I've finally progressed far enough down on my TODO list that resolving the vsgXchange/Assimp build issues is next item for me to tackle. It's end day here right now so I'll begin tackling it tomorrow.  Will likely experiment with a couple of different approaches before settling on a final path forward.  

If there is any insights/suggestions that would be worth me consider please chip in.

**Comment by robertosfield** [comment]
I've now get vsgXchange compiling against assump 5.0.0 and 5.1.4, in the branch:

   [Assimp_5_1_build]( https://github.com/vsg-dev/vsgXchange/tree/Assimp_5_1_build)

I had to add some cmake Assimp version checking and setup of defines that are passed to the c++ build to enable the code to determine which code paths are required.  I had to do this as the Assimp headers don't seem to have any versioning you can use to check which version is being compiled against.  

While I have things compiling the branch still doesn't function the same across 5.0.0 and 5.1.x as there are some material differences between the two that I'm having to try to figure out as there isn't always a straight forward 1:! mapping.

**Comment by robertosfield** [comment]
I have finally got a reasonable solution to the Assimp  5,1,x through Assimp master support whilst maintaining 5.0.0 build.  Took quite a bit of comparing changes to Assimp and trail and error of trying to get something working on the vsgXchange side. #86.
