### ISSUE TITLE
Build fails after VSG matrix stack change

### ISSUE THREAD

**Issue by michaelveth** [vsg-dev/vsgXchange#70]
SceneBuilder is trying to construct using deprecated float matrices.  I have a fix and will submit a PR.

**Comment by robertosfield** [comment]
The changes look sensible, but I'm perplexed why I've not been seeing a build failure as I'm using Ubuntu 21.04.  What are the build errors that you are seeing?  

I'd like to get to the bottom of it as there may be issues lurking beyond just the build issues you've seen, and what would be the most appropriate changes.

**Comment by michaelveth** [comment]
It appears to be failing to construct the float template.  Here's an example:
`In file included from /opt/vulkan_scene_graph/include/vsg/core/External.h:15,
                 from /opt/vulkan_scene_graph/include/vsg/all.h:25,
                 from /home/mike/vsgXchange/src/osg/BuildOptions.h:3,
                 from /home/mike/vsgXchange/src/osg/SceneBuilder.h:12,
                 from /home/mike/vsgXchange/src/osg/SceneBuilder.cpp:13:
/opt/vulkan_scene_graph/include/vsg/core/Inherit.h: In instantiation of ‘static vsg::ref_ptr<R> vsg::Inherit<ParentClass, Subclass>::create(Args&& ...) [with Args = {vsg::t_mat4<float>&}; ParentClass = vsg::Transform; Subclass = vsg::MatrixTransform]’:
/home/mike/vsgXchange/src/osg/SceneBuilder.cpp:548:98:   required from here
/opt/vulkan_scene_graph/include/vsg/core/Inherit.h:66:38: error: no matching function for call to ‘vsg::MatrixTransform::MatrixTransform(vsg::t_mat4<float>&)’
   66 |             return ref_ptr<Subclass>(new Subclass(args...));`

The key message is here: `error: no matching function for call to ‘vsg::MatrixTransform::MatrixTransform(vsg::t_mat4<float>&)’`. 

I'm surprised you are not seeing the error.  Let me know if you would like more information.

**Comment by robertosfield** [comment]
On Wed, 8 Dec 2021 at 22:56, michaelveth ***@***.***> wrote:

> It appears to be failing to construct the float template. Here's an
> example:
> In file included from
> /opt/vulkan_scene_graph/include/vsg/core/External.h:15, from
> /opt/vulkan_scene_graph/include/vsg/all.h:25, from
> /home/mike/vsgXchange/src/osg/BuildOptions.h:3, from
> /home/mike/vsgXchange/src/osg/SceneBuilder.h:12, from
> /home/mike/vsgXchange/src/osg/SceneBuilder.cpp:13:
> /opt/vulkan_scene_graph/include/vsg/core/Inherit.h: In instantiation of
> ‘static vsg::ref_ptr<R> vsg::Inherit<ParentClass, Subclass>::create(Args&&
> ...) [with Args = {vsg::t_mat4<float>&}; ParentClass = vsg::Transform;
> Subclass = vsg::MatrixTransform]’:
> /home/mike/vsgXchange/src/osg/SceneBuilder.cpp:548:98: required from here
> /opt/vulkan_scene_graph/include/vsg/core/Inherit.h:66:38: error: no
> matching function for call to
> ‘vsg::MatrixTransform::MatrixTransform(vsg::t_mat4<float>&)’ 66 | return
> ref_ptr<Subclass>(new Subclass(args...));
>
> The key message is here: error: no matching function for call to
> ‘vsg::MatrixTransform::MatrixTransform(vsg::t_mat4<float>&)’.
>
I'm surprised you are not seeing the error. Let me know if you would like
> more information.
>

This is vsgXchange master's SceneBuilder.cpp:

           // need to insert a transform
            vsg::dmat4 vsgmatrix = vsg::dmat4(matrix(0, 0), matrix(0, 1),
matrix(0, 2), matrix(0, 3),
                                              matrix(1, 0), matrix(1, 1),
matrix(1, 2), matrix(1, 3),
                                              matrix(2, 0), matrix(2, 1),
matrix(2, 2), matrix(2, 3),
                                              matrix(3, 0), matrix(3, 1),
matrix(3, 2), matrix(3, 3));

            vsg::ref_ptr<vsg::MatrixTransform> transform =
vsg::MatrixTransform::create(vsgmatrix);

So... I've already checked in the change to use dmat4.  My guess is you
updated the VSG, but not vsgXchange.

The changes that forced this was the introduction of explicit in the
declaration of MatrixTransform(dmat4) constructor so the implicit
conversion from mat4 to dmat4 is no longer allowed.

Could you set aside you changes and sync your vsgXchange with
vsg-dev/vsgXchange master and see how the build goes.  If there are any
remaining problems we can look at those.

Cheers,
Robert.



>

**Comment by michaelveth** [comment]
Yes. Embarrassing to say, but this was git bafoonery on my part! Sorry for the false issue.

Build perfectly with your push from 8 Dec (ce1806a7dbfb791328d1b33ac3d319e72b08d7ff).

Mike
